# Generated by Django 4.2.16 on 2024-12-31 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('logistics', '0002_alter_package_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.warehouse', verbose_name='发货仓库'),
        ),
    ]
