# Generated by Django 4.2.16 on 2024-12-30 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0002_alter_sku_suppliers_list_alter_spu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='仓库ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='仓库地址')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库列表',
                'db_table': 'storage_warehouse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='库存ID')),
                ('stock_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量')),
                ('avg_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='平均成本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.sku', verbose_name='关联SKU')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存列表',
                'db_table': 'storage_stock',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sku'], name='storage_sto_sku_id_2a97df_idx'), models.Index(fields=['warehouse'], name='storage_sto_warehou_99a353_idx')],
                'unique_together': {('warehouse', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=10, verbose_name='货区编码')),
                ('area_name', models.CharField(max_length=20, verbose_name='货区名称')),
                ('area_type', models.CharField(choices=[('NORMAL', '普通区'), ('CONSUMABLE', '耗材区'), ('REQUISITION', '领用区')], default='NORMAL', max_length=20, verbose_name='货区类型')),
                ('location_code', models.CharField(max_length=10, verbose_name='货位编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '货区货位',
                'verbose_name_plural': '货区货位列表',
                'db_table': 'storage_allocation',
                'ordering': ['warehouse', 'area_code', 'location_code'],
                'unique_together': {('warehouse', 'area_code', 'location_code')},
            },
        ),
    ]
