# Generated by Django 4.2.16 on 2024-12-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='suppliers_list',
            field=models.TextField(blank=True, default='[]', verbose_name='供应商列表'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.category', verbose_name='类目'),
        ),
    ]
