# Generated by Django 4.2.16 on 2024-12-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('platform', '平台订单'), ('influencer', '达人订单'), ('offline', '线下订单'), ('employee', '员工自购')], default='platform', help_text='订单来源类型', max_length=20, verbose_name='订单类型'),
        ),
    ]
