# Generated by Django 4.2.16 on 2024-12-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_postcode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='邮编'),
        ),
    ]
