# Generated by Django 4.2.16 on 2024-12-31 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0003_order_recipient_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='销售员'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('platform', '平台订单'), ('influencer', '达人订单'), ('offline', '线下订单'), ('requisition', '员工领用'), ('employee', '员工自购')], default='platform', help_text='订单来源类型', max_length=20, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_order_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
